Splitting the route by org units
dhis2/integration-t2a pull request #3
Opened 2022-01-16 17:22 UTC by chathurawidanage

2022-01-17 05:51 UTC, mortenoh approved these changes

2022-01-17 05:51 UTC, mortenoh commented on src/main/java/org/hisp/dhis/integration/t2a/processors/AnalyticsGridQueryBuilder.java
> +    private static final Logger LOG = LogManager.getLogger( AnalyticsGridQueryBuilder.class );
Maybe you can use `@Log4j2` annotation for this? like we do in `dhis2-core` (also make sure that the log4j included is not the vulnerable one)

2022-01-17 05:51 UTC, mortenoh commented on src/main/java/org/hisp/dhis/integration/t2a/routes/MultiDimensionSplitter.java
> +import org.hisp.dhis.integration.t2a.model.*;
Please don't use import collapse (we usually put it to 99 in our IDEs)

2022-01-17 07:57 UTC, claudemamo requested changes
This PR is duplicating my work which I had agreed to implement with @bobjolliffe.

2022-01-17 10:27 UTC, bobjolliffe requested changes
I think this will be too fine grained.  It is good to split along the OU dimension, but by each OU is too much.  The problem we foresee is a very large set (0.5 million sites).  Without splitting the resultset will be too large,  But splitting on each OU will be too many requests.  My view would be that Split.java needs to have not a OrganisationUnit but a Collection<OrganisationUnit>.  So we can have configurable chunks ... eg 100 or 1000 orgunits at a time.

2022-01-17 10:42 UTC, chathurawidanage commented
I agree bob. This change can be easily incorporated. I'll wait till we merge @claudemamo 's PR. Then I'll rebase on main branch and remove redundant stuff and implement grouping if it's not available.

One question though. Should we worry about character limit for GET requests when sending multiple ous? I guess it ranges from min of 2048 to few thousands and depends on how it's configured. Usually it's safer to aim at 2048 right?

2022-01-18 13:20 UTC, chathurawidanage commented
Closing the PR since this is obsolete.

2022-01-18 13:20 UTC, closed without merging